Paginate = 5
baseurl = "http://orlade.github.io"
languageCode = "en-au"
theme = "hyde"
title = "Software adventures and thoughts"
[Author]
name = "Oliver Lade"
[Permalinks]
post = "/:year/:month/:filename/"
tutorials = "/:filename/"
[params]
disqus = "orlade"
domain = "github.orlade.io"
github = "https://github.com/orlade"
googletrackingid = ""
info = "http://www.orlade.github.io"
linkedin = "https://au.linkedin.com/in/oliverlade"
