baseurl = "http://orlade.github.io"
languageCode = "en-au"
title = "Software adventures and thoughts"
theme = "hyde"
Paginate = 5

[Author]
 name = "Oliver Lade"

[Permalinks]
 post = "/:year/:month/:filename/"
 tutorials = "/:filename/"

[params]
 info = "http://www.orlade.github.io"
 github = "https://github.com/orlade"
 linkedin = "https://au.linkedin.com/in/oliverlade"
 disqus = "orlade"
 googletrackingid = ""
 domain = "github.orlade.io"
